### ISSUE TITLE
Przykłady / hasztagi / memy z polskiego Mastodona

### ISSUE THREAD

**Issue by lwojcik** [lwojcik/Mastodon-Poradnik#1]
https://github.com/lwojcik/Mastodon-Poradnik#kultura-na-mastodonie-jest-jaka%C5%9B-taka-dziwna

W tym pytaniu fajnie byłoby zawrzeć podobne przykłady, ale odnoszące się do naszej polskiej części Mastodona czy ogólnie fediwersum. Zdaję sobie sprawę, że może nie być ich wiele, ale może ja jeszcze mało widzę. :)

Przykłady z zagranicznego Mastodona, które "siadły" też i u nas również mogłyby się tu pojawić - na szybko przychodzą mi do głowy Follow Friday czy John Mastodon.

Może jest jakiś zwyczaj, który przynieśliśmy na Mastodona z innych polskich społecznościówek?

**Comment by sjbat** [comment]
Z twittera przyszedł chyba zwyczaj "Dzień dobry, smacznej kawusi".

Adoptuję się z powoli, ale z powodzeniem "grupy dyskusyjne" Guppe Groups np. @rower@a.gup.pe czy @postpunk@a.gup.pe
O grupach GG:
https://zb3.org/m0bi13/przekluwacz-baniek-w-fediversum-guppe-groups
https://zb3.org/m0bi13/polskie-grupy-guppe-groups

Raczej polski jest hashtag #ExiTT - migracja z twittera, nie spotkałem się z nim na zagranicznych kontach. Powiązany z nim hashtag #FediPomoc i grupa guppe @fedipomoc@a.gup.pe (raczkuje).

Tak na szybko.

Dzięki za Mastodon-Poradnik po polsku :)

**Comment by lwojcik** [comment]
> Raczej polski jest hashtag #ExiTT

O, no faktycznie, dopiszę.

> Adoptuję się z powoli, ale z powodzeniem "grupy dyskusyjne" Guppe Groups

Temu się muszę przyjrzeć bliżej, ale też brzmi dobrze.

**Comment by lwojcik** [comment]
Zamykam. Trochę się ten rozdział już rozrósł i wygląda już całkiem nieźle - a jak wpadnie mi coś nowego i wartego dodania, to otworzę nowe zadanie.
