### ISSUE TITLE
Pytanie - kopia zapasowa konta na mastodonie

### ISSUE THREAD

**Issue by olekstomek** [lwojcik/Mastodon-Poradnik#27]
https://github.com/lwojcik/Mastodon-Poradnik#jak-stworzy%C4%87-kopi%C4%99-zapasow%C4%85-mojego-konta-na-mastodonie

Czy to oznacza że jeżeli manualnie nie zrobię kopii swojego konta i jeżeli instancja na której mam konto zostanie usunięta lub bezpowrotnie uszkodzona to wtedy tracę konto i historię konta?

**Comment by lwojcik** [comment]
W dużym skrócie - tak. Rozwinę tę wypowiedź jak siądę do komputera z klawiaturą, daj mi chwilę.

**Comment by olekstomek** [comment]
Super, dzięki!

**Comment by lwojcik** [comment]
OK, mogę już rozwinąć wypowiedź.

Instancje Mastodona mogą znikać w różnych okolicznościach, ale najbardziej prawdopodobne są dwie:

1. Administracja decyduje się zamknąć / usunąć instancję,
2. Serwer lub jakiś inny istotny komponent instancji ulega awarii i giną dane użytkowników.

W obu przypadkach prawdopodobieństwo utraty własnych danych jest dość spore i dużo tu zależy od administracji instancji i jej poczucia odpowiedzialności wobec użytkowników.

Istnieje dokument zwany [Mastodon Server Covenant](https://joinmastodon.org/pl/covenant). O ile raczej nie da się go traktować jak zobowiązania prawnego, o tyle można bezpiecznie przyjąć, że każdy właściciel serwera musiał się na niego natknąć przy uruchamianiu swojego serwera. Natomiast właściciele serwerów, których adresy da się znaleźć na [oficjalnej stronie Mastodona](https://joinmastodon.org/pl/servers), potwierdzają zapoznanie się z nim i zobowiązują się do jego przestrzegania.

Przyjmujemy także, że serwery Mastodona otwarte dla użytkowników są zakładane przez odpowiedzialnych ludzi, świadomych tego, że biorą na siebie wymagającą rolę dostawcy usług.

I teraz rozważmy oba przypadki.

## Administracja decyduje się zamknąć / usunąć instancję

Mastodon Server Covenant sugeruje, że użytkownicy powinni zostać uprzedzeni co najmniej na 3 miesiące przed planowanym zamknięciem serwera. Jak dotąd widziałem tylko jedną dużą instancję, która się zamknęła w 2022: [mastodon.technology](https://ashfurrow.com/blog/mastodon-technology-shutdown/) i tam użytkownicy faktycznie dostali czas na migrację kont.

Wraz ze wzrostem użytkowników fediwersum takie sytuacje mogą się powtarzać. Prowadzenie serwera nie jest biznesem. Koszty serwerów mogą często rosnąć z dnia na dzień. Mimo wszystko odpowiedzialni administratorzy _nie powinni_ zamykać swoich instancji z dnia na dzień.

## Uszkodzenie danych w wyniku awarii serwera

Tu Mastodon Server Covenant wyraża się tak: administratorzy powinni tworzyć kopie zapasowe codziennie. Można ten proces zautomatyzować w oparciu o gotowe rozwiązania i wiedzę z sieci.

Jeśli administracja nie może odtworzyć serwera z kopii zapasowych, lub ich nie posiada - no to niestety nie ma ratunku.

I przy okazji ciekawostka - jeśli uszkodzona instancja była dobrze sfederowana (czyli jej użytkownicy komunikowali się z ludźmi z wielu różnych serwerów), to część historii wpisów może być do odzyskania z cache’u innych instancji. Dla przykładu, moje konto na nieistniejącej już jednoosobowej instancji ([lukem@mastodon.lukem.net](mailto:lukem@mastodon.lukem.net)) da się odnaleźć przez wyszukiwarkę na mstdn.social i w ten sposób przeczytać część historii moich wpisów. Ale nie traktuję tego jak pewnik - mstdn.social może prędzej czy później usunąć nieistniejące treści z nieistniejących instancji.

## No dobrze Łukasz, a da się może jakoś rozpoznać czy serwer Mastodona jest “pewny” i nie zostawi mnie z ręką w nocniku?

Tak ze stuprocentową pewnością nie. To jest zawsze kwestia zaufania do administracji. Ale pewne rzeczy da się wysondować z zewnątrz i wyciągnąć wnioski co do tego, kto sumiennie odrabia pracę domową.

1. Warto sprawdzić, kto faktycznie stoi za daną instancją. Czy ta osoba jest znana z imienia i nazwiska. A jeżeli to stowarzyszenie / fundacja - warto sprawdzić, czy faktycznie istnieje, i dlaczego w ogóle bawi się w prowadzenie instancji.
1. A jeśli mówimy o instancji mastodon.social czy mastodon.online - to są to instancje oficjalne, prowadzone przez organizację non-profit za pieniądze z dotacji. Wydaje mi się, że przynajmniej jedna będzie istnieć zawsze jako punkt startowy dla nowych użytkowników lub poligon doświadczalny dla nowych funkcji.
1. Warto sprawdzić, czy administracja instancji sama w ogóle jej używa. W zagranicznym fediwersum administratorzy instancji to osoby bardzo wokalne i ich aktywność przekłada się też na ich widoczność / opiniotwórczość. Nawet w tak hermetycznym środowisku jak fediwersum takie osoby ryzykują własnym wizerunkiem i raczej nie mogą sobie pozwolić na szkolne błędy. W Polsce ten efekt nie jest jeszcze aż tak widoczny, bo polskojęzyczna społeczność fediwersum jest o wiele mniejsza - ale z biegiem czasu to się pewnie zacznie zmieniać.
1. Warto sprawdzić, jak długo instancja istnieje i ilu ma użytkowników. Z dużą ostrożnością powiedziałbym, że jako potencjalny użytkownik ufam bardziej instancjom, które istniały przed rokiem 2022 - bo to oznacza, że miały czas na naukę i być może przetrwały już kilka fal nowych użytkowników, więc każda kolejna raczej im nie zagrozi. Ale są wyjątki od tej reguły.
1. Warto sprawdzić kwestie finansowania - czy administracja przyjmuje dotacje / patronaty na działalność serwera, a jeśli nie, to skąd czerpie środki i na jak długo one wystarczą (i może także się dorzucić?). W dobrze prowadzony serwer dla dużej liczby osób trzeba włożyć czas, energię i pieniądze.
1. No i wreszcie, w razie wątpliwości warto najzwyczajniej w świecie popytać administrację o różne detale - w tym o to, gdzie ulokowany jest serwer, czy są tworzone kopie zapasowe, i czy kiedykolwiek ktoś sprawdził, czy te kopie zapasowe da się przywrócić. Kompetentna administracja nie będzie mieć problemu z odpowiedzią, a ta mniej kompetentna przynajmniej odczuje presję, że może warto zrobić coś lepiej. :)

Także podsumowując - odpowiedź nadal brzmi “tak” i jeśli zależy nam na zachowaniu naszych treści, to ufamy administracji naszej instancji ORAZ tworzymy własne kopie zapasowe.

Chyba to dopiszę jako dodatkowe pytanie, tylko muszę skrócić odpowiedź. :)

**Comment by olekstomek** [comment]
Dzięki za obszerną odpowiedź! Jest to bardzo pomocne i na pewno będzie to pomocne dla innych którzy przeczytają te informacje. :)
