### ISSUE TITLE
mały błąd językowy

### ISSUE THREAD

**Issue by jklawiter** [lwojcik/Mastodon-Poradnik#29]
czym jest mastodon…
 To takie skrzyżowanie Twittera z e-mailem, ale ~~nieco~~ różniące się nieco od nich **obu**.

**Comment by lwojcik** [comment]
Dzięki @jklawiter!

Wzorem innych moich projektów dodałem plik AUTORZY - jeżeli masz ochotę, dopisz się tam. :)

**Comment by krystian3w** [comment]
Ja bym wywalił drugie nieco i obu byłoby zbędne.

**Comment by lwojcik** [comment]
> Ja bym wywalił drugie nieco i obu byłoby zbędne.

Aktualne brzmienie (już po poprawce zgłoszonej przez @jklawiter)  jest takie ([można sprawdzić tutaj](https://mastodon-poradnik.pl/czym-jest-mastodon/)):

 > To takie skrzyżowanie Twittera z e-mailem, ale różniące się nieco od nich obu.
 
Mogłoby też być tak:

> To takie skrzyżowanie Twittera z e-mailem, ale nieco różniące się od nich.
 
 Dla mnie obie wersje brzmią OK, ale pomyślę jeszcze nad tym.
