### ISSUE TITLE
Inkluzywność języka + różne poprawki

### ISSUE THREAD

**Issue by lwojcik** [lwojcik/Mastodon-Poradnik#4]
Jak zwykle przy tłumaczeniu treści z angielskiego, mam ogromny problem z jednolitym użyciem zaimków. Autorka oryginału jest trans-kobietą i tam, gdzie ona mówi swoim głosem, tam ja też używam żeńskich zaimków. Ale nie wiem co zrobić, gdy autorka mówi do osoby czytającej. Jako białemu cis facetowi brakuje mi niestety odpowiedniej perspektywy. :(

Z historycznego punktu widzenia Mastodon powstał z myślą oraz był współtworzony przez osoby marginalizowane. Zakładanie w treści jednej konkretnej płci jest moim zdaniem mocno nie na miejscu. I może też trzeba tym poradnikiem otworzyć oczy innym i powiedzieć głośno, że Mastodon nie jest kolejną platformą dla uprzywilejowanych białych cis-facetów.

Opcje, które przychodzą mi do głowy:

1. Uwzględnianie dwóch zaimków z użyciem nawiasu, np. _zrobiłem(am), zmieniłeś(aś)_ - tutaj niestety wciąż obracamy się wokół binarnych zaimków + nie wiem, czy dobrze się to czyta,

2. Żonglowanie różnymi zaimkami w treści - zabieg, który widziałem kiedyś w innym poradniku. Raz mówimy _zrobiłeś_, raz _zrobiłaś_, raz _zrobiłoś_, itp. i dbamy o to, aby te formy były stosowane równomiernie w całej treści poradnika,

3. Przyjęcie uniwersalnej formy typu _zrobił\*ś, napisał\*m_ - osobiście rzadko widzę taką formę na piśmie.

4. Unikanie języka nacechowanego płciowo - nie zawsze się da i często to brzmi o wiele gorzej.

Sugestie i komentarze mile widziane.

**Comment by sjbat** [comment]
Pisząc tootoriale wybieram 4, unikam języka nacechowanego płciowo. To dość trudne, zwłaszcza jeśli chcę uniknąć sformułowań potworków (dla mnie) "osoby admińskie" - piszę "osoby zajmujące się administracją instancjami". Nie administratorzy i administratorki. Po pewnym czasie nabrałem wprawy, potrafię napisać sporo tekstu bez użycia form nacechowanych płciowo.
Popełniałem "błędy", np. "Czym-mozecie-byc-zdziwieni-po-przejsciu-z-twittera-do-mastodon", zmieniłem na "Co może cię zdziwić po przejściu z Twittera do Mastodona?" i tej formy bezpośredniej "ty" się trzymam. Łatwiej.
Przy tłumaczeniu masz trudniej. Ale zrobiłem(am), zmieniłeś(aś) mozna zmienić na Aby zrobić, by to zostało zrobione, zmienione, zmiana tego wymaga itp.
Moje trzy grosze i odrobina doświadczenia.

**Comment by lwojcik** [comment]
Dzięki @sjbat! 

Też się na razie skłaniam się ku opcji 4.
